[workspace]
members = [
    "day01",
    "day01pt2",
    "day02",
    "day02pt2",
    "day03",
    "day03pt2",
    "day04",
    "day04pt2",
    "day05",
]

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = "thin"
